---
projects:
- name: "OM3 at Heathrow Airport (Heathrow Boutique)"
  included-applications:
  - name: flamingo
  - name: akeneo
  - name: keycloak
applications:
- name: flamingo
  title: Flamingo Core Product
  summary: Flamingo is the customer facing ecommerce frontend.
  properties:
    deployment: kubernetes
    healthCheckPath: /healthcheck
    # set this to a different name if k8s deployment name differs
    k8sDeploymentName: flamingo
    # set this to a different name if k8s deployment name differs
    k8sHealthCheckServiceName: flamingo-healthcheckservice
- name: newservice
  properties:
    deployment: kubernetes
    healthCheckPath: /healthcheck
- name: akeneo
  title: Flamingo Core Product
  summary: Flamingo is the customer facing ecommerce frontend.
  properties:
    deployment: kubernetes
    healthCheckPath: /en/status/healthcheck
# a app without an healtcheck (the fallback to check for non errors statuscode is used)
- name: keycloak
  title: SSO Server
  summary: The keycloak is the central IRM/SSO for system users and customers and therefore single source of user passwords, roles and rights (human as well as systems)
  technology: keycloak
  properties:
    deployment: kubernetes
    comments: The project specific container should just add the keycloak theme to the om3 base keycloak container.