name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24', '1.*' ]
    name: Tests
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test
        run: CGO_ENABLED=1 go test -race ./...
  static-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.*' ]
    name: Static checks
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Go Vet
        run: go vet ./...
      - name: Go Fmt
        run: |
          fmt=$(gofmt -l .)
          test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
      - name: Go Staticcheck
        run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...
      - name: Goimports
        run: |
          go run golang.org/x/tools/cmd/goimports@latest -w .
          git diff --quiet || (echo 'goimports requires code cleanup:' ; git diff ; exit 1)
